### ISSUE TITLE
Error running hugo server  

### ISSUE THREAD

**Issue by odidev** [jasonrandrews/arm-software-developers#6]
Hi Team, 

I am working on running the local version of the repository and deploying the same although I am getting error while running the “hugo server” command. I have followed the steps below: 

1. git clone --recurse-submodules https://github.com/jasonrandrews/arm-software-developers.git 
2. npm install 
3. Followed the [installation guide](https://www.docsy.dev/docs/get-started/docsy-as-module/installation-prerequisites/) and installed hugo, go, git vcs, postcss and nodejs 
4. Run “hugo server” command 
5. Hugo deploy 

Currently I am getting the error below while running the hugo server command, please find below the logs: 

```
ubuntu@ip-172-31-12-172:~/arm-software-developers$ hugo server 

hugo: downloading modules … 

go: downloading github.com/google/docsy v0.4.0 

go: downloading github.com/google/docsy/dependencies v0.4.0 

go: upgraded github.com/google/docsy/dependencies v0.2.0 => v0.4.0 

hugo: collected modules in 14865 ms 

Built in 2040 ms 

Error: Error building site: EXECUTE-AS-TEMPLATE: failed to transform "json/offline-search-index.json" (application/json): failed to parse Resource "json/offline-search-index.json" as Template:: template: json/offline-search-index.json:5: unclosed action 
```

Please share any pointers to resolve the same, do correct me if I missed anything here. Thanks in advance!

**Comment by pareenaverma** [comment]
Hi, 

Please confirm the Hugo version you are using. The default hugo version downloaded from the ubuntu package manager will have this error. You will need to download an extended release version as documented here https://www.docsy.dev/docs/get-started/docsy-as-module/installation-prerequisites/

For example: hugo version
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio

**Comment by jsrz** [comment]
@odidev, @pareenaverma perhaps an update to the instruction on this repo stating that the extended version of huge is needed would be a good idea. This way other people don't run into this issue.

**Comment by pareenaverma** [comment]
Hi Julio,

Yes indeed I'll update the instructions - the extended version is mentioned in the Installation Pre-requisites link but I'll make a separate mention.

Couple of notes though: For content contribution you don't need to actually install/run Hugo. That's more for the website developers(our team). Content contributors only need to add the Learning Path and How-to content under the relevant content/en directory structure.
For ease of use we have created templates for these learning paths/how-to's if you don't want to create the markdown files from scratch. They are under https://github.com/jasonrandrews/arm-software-developers/tree/master/dev_templates
[https://opengraph.githubassets.com/308aa5078bb9e9eebcc764c77e98ac87832a4831e0497e2f2f96a99545f911ed/jasonrandrews/arm-software-developers]<https://github.com/jasonrandrews/arm-software-developers/tree/master/dev_templates>
arm-software-developers/dev_templates at master · jasonrandrews/arm-software-developers<https://github.com/jasonrandrews/arm-software-developers/tree/master/dev_templates>
Contribute to jasonrandrews/arm-software-developers development by creating an account on GitHub.
github.com


Again, I can setup a quick call with you all to show you the files you need to modify/add if needed. Let me know

Thanks
Pareena
________________________________
